version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile

  prom:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 127.0.0.1:9091:9090

  grafana:
    image: grafana/grafana
    ports:
      - 127.0.0.1:3001:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_USERS_ALLOW_SIGN_UP=false
#      - GF_SERVER_DOMAIN=myrul.com
#      - GF_SMTP_ENABLED=true
#      - GF_SMTP_HOST=smtp.gmail.com:587
#      - GF_SMTP_USER=myadrress@gmail.com
#      - GF_SMTP_PASSWORD=mypassword
#      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
