// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld/helloworld.proto

package helloworld

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73149fedf49f4319, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_73149fedf49f4319, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type EhloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EhloRequest) Reset()         { *m = EhloRequest{} }
func (m *EhloRequest) String() string { return proto.CompactTextString(m) }
func (*EhloRequest) ProtoMessage()    {}
func (*EhloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73149fedf49f4319, []int{2}
}

func (m *EhloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EhloRequest.Unmarshal(m, b)
}
func (m *EhloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EhloRequest.Marshal(b, m, deterministic)
}
func (m *EhloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EhloRequest.Merge(m, src)
}
func (m *EhloRequest) XXX_Size() int {
	return xxx_messageInfo_EhloRequest.Size(m)
}
func (m *EhloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EhloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EhloRequest proto.InternalMessageInfo

func (m *EhloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EhloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EhloReply) Reset()         { *m = EhloReply{} }
func (m *EhloReply) String() string { return proto.CompactTextString(m) }
func (*EhloReply) ProtoMessage()    {}
func (*EhloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_73149fedf49f4319, []int{3}
}

func (m *EhloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EhloReply.Unmarshal(m, b)
}
func (m *EhloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EhloReply.Marshal(b, m, deterministic)
}
func (m *EhloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EhloReply.Merge(m, src)
}
func (m *EhloReply) XXX_Size() int {
	return xxx_messageInfo_EhloReply.Size(m)
}
func (m *EhloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EhloReply.DiscardUnknown(m)
}

var xxx_messageInfo_EhloReply proto.InternalMessageInfo

func (m *EhloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SaySixSixSixRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaySixSixSixRequest) Reset()         { *m = SaySixSixSixRequest{} }
func (m *SaySixSixSixRequest) String() string { return proto.CompactTextString(m) }
func (*SaySixSixSixRequest) ProtoMessage()    {}
func (*SaySixSixSixRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73149fedf49f4319, []int{4}
}

func (m *SaySixSixSixRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaySixSixSixRequest.Unmarshal(m, b)
}
func (m *SaySixSixSixRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaySixSixSixRequest.Marshal(b, m, deterministic)
}
func (m *SaySixSixSixRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaySixSixSixRequest.Merge(m, src)
}
func (m *SaySixSixSixRequest) XXX_Size() int {
	return xxx_messageInfo_SaySixSixSixRequest.Size(m)
}
func (m *SaySixSixSixRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaySixSixSixRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaySixSixSixRequest proto.InternalMessageInfo

type SaySixSixSixReply struct {
	SixSixSixInt         int64    `protobuf:"varint,1,opt,name=sixSixSixInt,proto3" json:"sixSixSixInt,omitempty"`
	SixSixSixString      string   `protobuf:"bytes,2,opt,name=sixSixSixString,proto3" json:"sixSixSixString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaySixSixSixReply) Reset()         { *m = SaySixSixSixReply{} }
func (m *SaySixSixSixReply) String() string { return proto.CompactTextString(m) }
func (*SaySixSixSixReply) ProtoMessage()    {}
func (*SaySixSixSixReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_73149fedf49f4319, []int{5}
}

func (m *SaySixSixSixReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaySixSixSixReply.Unmarshal(m, b)
}
func (m *SaySixSixSixReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaySixSixSixReply.Marshal(b, m, deterministic)
}
func (m *SaySixSixSixReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaySixSixSixReply.Merge(m, src)
}
func (m *SaySixSixSixReply) XXX_Size() int {
	return xxx_messageInfo_SaySixSixSixReply.Size(m)
}
func (m *SaySixSixSixReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SaySixSixSixReply.DiscardUnknown(m)
}

var xxx_messageInfo_SaySixSixSixReply proto.InternalMessageInfo

func (m *SaySixSixSixReply) GetSixSixSixInt() int64 {
	if m != nil {
		return m.SixSixSixInt
	}
	return 0
}

func (m *SaySixSixSixReply) GetSixSixSixString() string {
	if m != nil {
		return m.SixSixSixString
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
	proto.RegisterType((*EhloRequest)(nil), "helloworld.EhloRequest")
	proto.RegisterType((*EhloReply)(nil), "helloworld.EhloReply")
	proto.RegisterType((*SaySixSixSixRequest)(nil), "helloworld.SaySixSixSixRequest")
	proto.RegisterType((*SaySixSixSixReply)(nil), "helloworld.SaySixSixSixReply")
}

func init() { proto.RegisterFile("helloworld/helloworld.proto", fileDescriptor_73149fedf49f4319) }

var fileDescriptor_73149fedf49f4319 = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x2a, 0xd6, 0x8e, 0x81, 0xe2, 0x48, 0x35, 0xa4, 0x88, 0xba, 0xa0, 0xf4, 0x14, 0x45,
	0x8f, 0x82, 0x87, 0x82, 0xa8, 0xb7, 0x90, 0x1c, 0x3c, 0xaf, 0x3a, 0xa4, 0x81, 0xcd, 0x87, 0x9b,
	0x15, 0xbb, 0xff, 0xd4, 0x9f, 0x23, 0xbb, 0x69, 0xec, 0x56, 0x6b, 0x21, 0x87, 0x99, 0x37, 0x6f,
	0x5e, 0xf6, 0x3d, 0x06, 0x46, 0x53, 0x12, 0xa2, 0xfa, 0xac, 0xa4, 0x78, 0xbb, 0x5c, 0x94, 0x51,
	0x2d, 0x2b, 0x55, 0x21, 0x2c, 0x10, 0xc6, 0xc0, 0x7f, 0x34, 0x5d, 0x42, 0xef, 0x1f, 0xd4, 0x28,
	0x44, 0xd8, 0x2e, 0x79, 0x41, 0x81, 0x77, 0xea, 0x8d, 0xfb, 0x89, 0xad, 0xd9, 0x05, 0xc0, 0x9c,
	0x53, 0x0b, 0x8d, 0x01, 0xf4, 0x0a, 0x6a, 0x1a, 0x9e, 0x75, 0xa4, 0xae, 0x65, 0x67, 0xb0, 0x77,
	0x3f, 0x5d, 0x2f, 0x75, 0x0e, 0xfd, 0x96, 0xb2, 0x5e, 0x69, 0x08, 0x07, 0x29, 0xd7, 0x69, 0x3e,
	0x6b, 0xbf, 0xb9, 0x22, 0xe3, 0xb0, 0xbf, 0x0c, 0x1b, 0x15, 0x06, 0x7e, 0xd3, 0x21, 0x4f, 0xa5,
	0xb2, 0x52, 0x5b, 0xc9, 0x12, 0x86, 0x63, 0x18, 0xfc, 0xf4, 0xa9, 0x92, 0x79, 0x99, 0x05, 0x9b,
	0xf6, 0x8f, 0xbf, 0xe1, 0xeb, 0x2f, 0x0f, 0x7a, 0x0f, 0x92, 0x48, 0x91, 0xc4, 0x3b, 0xd8, 0x4d,
	0xb9, 0xb6, 0xd6, 0x31, 0x88, 0x9c, 0x18, 0xdd, 0xc4, 0xc2, 0xc3, 0x15, 0x93, 0x5a, 0x68, 0xb6,
	0x81, 0xb7, 0xd0, 0x4b, 0xb9, 0x36, 0x7e, 0xf1, 0xc8, 0x25, 0x39, 0x21, 0x85, 0xc3, 0xbf, 0x83,
	0x76, 0x39, 0x06, 0xdf, 0xf5, 0x8a, 0x27, 0x2e, 0x71, 0x45, 0x38, 0xe1, 0xf1, 0xff, 0x04, 0xab,
	0x38, 0xb9, 0x82, 0x51, 0x5e, 0x45, 0x99, 0xac, 0x5f, 0x23, 0x9a, 0xf1, 0xa2, 0x16, 0xd4, 0x38,
	0x2b, 0x93, 0x81, 0x7d, 0xfb, 0xb3, 0xa9, 0x63, 0x73, 0x26, 0xb1, 0xf7, 0xb2, 0x63, 0xef, 0xe5,
	0xe6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xb9, 0xf3, 0x46, 0x4e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayEhlo(ctx context.Context, in *EhloRequest, opts ...grpc.CallOption) (*EhloReply, error)
	SaySixSixSix(ctx context.Context, in *SaySixSixSixRequest, opts ...grpc.CallOption) (*SaySixSixSixReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayEhlo(ctx context.Context, in *EhloRequest, opts ...grpc.CallOption) (*EhloReply, error) {
	out := new(EhloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayEhlo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SaySixSixSix(ctx context.Context, in *SaySixSixSixRequest, opts ...grpc.CallOption) (*SaySixSixSixReply, error) {
	out := new(SaySixSixSixReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SaySixSixSix", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayEhlo(context.Context, *EhloRequest) (*EhloReply, error)
	SaySixSixSix(context.Context, *SaySixSixSixRequest) (*SaySixSixSixReply, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (*UnimplementedGreeterServer) SayEhlo(ctx context.Context, req *EhloRequest) (*EhloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayEhlo not implemented")
}
func (*UnimplementedGreeterServer) SaySixSixSix(ctx context.Context, req *SaySixSixSixRequest) (*SaySixSixSixReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaySixSixSix not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayEhlo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EhloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayEhlo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayEhlo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayEhlo(ctx, req.(*EhloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SaySixSixSix_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaySixSixSixRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SaySixSixSix(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SaySixSixSix",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SaySixSixSix(ctx, req.(*SaySixSixSixRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "SayEhlo",
			Handler:    _Greeter_SayEhlo_Handler,
		},
		{
			MethodName: "SaySixSixSix",
			Handler:    _Greeter_SaySixSixSix_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "helloworld/helloworld.proto",
}
