version: "3.6"

services:
  postgres:
    image: postgres
    ports:
      - 55432:5432
    volumes:
      - ./initial.sql:/docker-entrypoint-initdb.d/initial.sql
      - ./initial.sh:/docker-entrypoint-initdb.d/initial.sh
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
